### ISSUE TITLE
Favicon and Social/OG images

### ISSUE THREAD

**Issue by brittneypostma** [Learn-Build-Teach/learnbuildteach.com#10]
- Take the circle logo and generate favicon image sizes using https://favicon.io/ or similar.
- Place favicon images inside static/img folder.
- Link to favicon and create meta tags for social images in a `<svelte:head>` tag inside of the `routes/__layout.svelte` file
![image](https://user-images.githubusercontent.com/45889730/136705672-ea504bba-201f-438d-bff2-df8aa145b1dc.png)

**Comment by avneesh0612** [comment]
Hey, can I work on it?

**Comment by brittneypostma** [comment]
Absolutely, any open issue is free to be worked on.

**Comment by avneesh0612** [comment]
Awesome! Can you assign it to me?

**Comment by avneesh0612** [comment]
Made a pr to fix it @brittneypostma
